import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { JSONSchema } from 'json-schema-to-typescript';
import { compile } from 'json-schema-to-typescript';
import ts from 'typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const BIOME_CONSTANTS_PATH = resolve(__dirname, '../src/constants/biome.ts');
const LEGACY_OUTPUT_PATH = resolve(__dirname, '../src/types.ts');
const GENERATED_DIR = resolve(__dirname, '../src/generated/biome');
const GENERATED_INDEX_PATH = resolve(GENERATED_DIR, 'index.ts');

const BANNER_COMMENT = `// This file was automatically generated by scripts/generate-biome-types.ts\n// Do not edit this file directly.\n`;

const MAX_DECLARATIONS_PER_FILE = 120;
const MAX_CHARACTERS_PER_FILE = 45_000;
const MAX_SLUG_LENGTH = 60;

interface DeclarationInfo {
  name: string;
  text: string;
  dependencies: Set<string>;
  charLength: number;
  order: number;
}

interface ModulePart {
  index: number;
  names: string[];
  declarations: DeclarationInfo[];
}

interface GeneratedModule {
  fileName: string;
  content: string;
  exports: string[];
}

interface ModuleGenerationResult {
  modules: GeneratedModule[];
  indexContent: string;
  legacyContent: string;
}

async function resolveSchemaUrl(): Promise<string> {
  const source = await readFile(BIOME_CONSTANTS_PATH, 'utf8');
  const match = source.match(/BIOME_SCHEMA_URL\s*=\s*['"]([^'"]+)['"]/);
  if (!match) {
    throw new Error(`Failed to resolve BIOME_SCHEMA_URL from ${BIOME_CONSTANTS_PATH}`);
  }
  return match[1];
}

async function fetchSchema(url: string): Promise<JSONSchema> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch schema from ${url}: ${response.status} ${response.statusText}`);
  }
  return response.json() as Promise<JSONSchema>;
}

async function generateTypes(): Promise<void> {
  const schemaUrl = await resolveSchemaUrl();
  const schema = await fetchSchema(schemaUrl);

  let typeSource = await compile(schema, 'BiomeConfig', {
    bannerComment: BANNER_COMMENT,
    style: {
      singleQuote: true,
      trailingComma: 'none',
    },
  });

  if (!typeSource.includes('export type BiomeConfig')) {
    typeSource = `${typeSource.trimEnd()}\n\nexport type BiomeConfig = Configuration;\n`;
  }

  const generationResult = splitTypesIntoModules(typeSource);
  await writeGeneratedArtifacts(generationResult);

  console.log(`Generated BiomeConfig types at ${LEGACY_OUTPUT_PATH}`);
}

try {
  await generateTypes();
} catch (error) {
  console.error('Failed to generate BiomeConfig types.');
  console.error(error);
  process.exitCode = 1;
}

function splitTypesIntoModules(source: string): ModuleGenerationResult {
  const trimmedSource = stripBanner(source, BANNER_COMMENT);
  const declarationNodes = collectDeclarations(trimmedSource);
  const declarations = enrichDeclarationsWithDependencies(declarationNodes);

  const adjacency = new Map<string, Set<string>>();
  for (const decl of declarations) {
    adjacency.set(decl.name, new Set(decl.dependencies));
  }

  const components = orderComponents(declarations, adjacency);
  const modules = packModules(components, declarations);
  const moduleFileNames = assignModuleFileNames(modules);
  const generatedModules = modules.map(module => buildModuleFile(module, modules, moduleFileNames));

  const indexContent = [BANNER_COMMENT.trimEnd(), '', ...generatedModules.map(module => `export * from './${module.fileName}';`), ''].join(
    '\n',
  );

  const legacyContent = [BANNER_COMMENT.trimEnd(), '', "export * from './generated/biome/index.ts';", ''].join('\n');

  return {
    modules: generatedModules,
    indexContent,
    legacyContent,
  };
}

function stripBanner(source: string, banner: string): string {
  if (!source.startsWith(banner)) {
    return source;
  }
  return source.slice(banner.length).replace(/^\s*/, '');
}

function collectDeclarations(source: string): Array<{
  name: string;
  text: string;
  node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration;
  order: number;
}> {
  const sourceFile = ts.createSourceFile('types.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const declarations: Array<{
    name: string;
    text: string;
    node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration;
    order: number;
  }> = [];

  let order = 0;
  for (const statement of sourceFile.statements) {
    if (!ts.isInterfaceDeclaration(statement) && !ts.isTypeAliasDeclaration(statement)) {
      continue;
    }

    const hasExport = statement.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword);
    if (!hasExport || !statement.name) {
      continue;
    }

    const name = statement.name.text;
    const text = source.slice(statement.getFullStart(), statement.getEnd()).trim();

    declarations.push({
      name,
      text,
      node: statement,
      order: order++,
    });
  }

  return declarations;
}

function enrichDeclarationsWithDependencies(
  entries: Array<{
    name: string;
    text: string;
    node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration;
    order: number;
  }>,
): DeclarationInfo[] {
  const nameSet = new Set(entries.map(entry => entry.name));
  const declarations: DeclarationInfo[] = [];

  for (const entry of entries) {
    const dependencies = collectDependencies(entry.node, nameSet);

    declarations.push({
      name: entry.name,
      text: entry.text,
      dependencies,
      charLength: entry.text.length,
      order: entry.order,
    });
  }

  return declarations;
}

function collectDependencies(node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration, nameSet: Set<string>): Set<string> {
  const dependencies = new Set<string>();

  const record = (identifier: string) => {
    if (nameSet.has(identifier) && identifier !== node.name.text) {
      dependencies.add(identifier);
    }
  };

  const visit = (child: ts.Node) => {
    if (ts.isTypeReferenceNode(child)) {
      extractNamesFromTypeReference(child).forEach(record);
    } else if (ts.isExpressionWithTypeArguments(child)) {
      const expr = child.expression;
      if (ts.isIdentifier(expr)) {
        record(expr.text);
      } else if (ts.isPropertyAccessExpression(expr)) {
        record(expr.name.text);
      }
    } else if (ts.isImportTypeNode(child)) {
      if (child.qualifier && ts.isIdentifier(child.qualifier)) {
        record(child.qualifier.text);
      }
    }

    ts.forEachChild(child, visit);
  };

  ts.forEachChild(node, visit);

  return dependencies;
}

function extractNamesFromTypeReference(node: ts.TypeReferenceNode): string[] {
  const names: string[] = [];
  const { typeName } = node;

  const collect = (entity: ts.EntityName) => {
    if (ts.isIdentifier(entity)) {
      names.push(entity.text);
    } else if (ts.isQualifiedName(entity)) {
      collect(entity.left);
      names.push(entity.right.text);
    }
  };

  if (ts.isIdentifier(typeName)) {
    names.push(typeName.text);
  } else {
    collect(typeName);
  }

  return names;
}

function orderComponents(declarations: DeclarationInfo[], adjacency: Map<string, Set<string>>): string[][] {
  const names = declarations.map(decl => decl.name);
  const scc = stronglyConnectedComponents(names, adjacency);
  const componentIndexByName = new Map<string, number>();
  scc.forEach((component, index) => {
    component.forEach(name => {
      componentIndexByName.set(name, index);
    });
  });

  const graph = new Map<number, Set<number>>();
  const inDegree = new Map<number, number>();

  scc.forEach((_, index) => {
    graph.set(index, new Set());
    inDegree.set(index, 0);
  });

  for (const [name, deps] of adjacency.entries()) {
    const dependantIndex = componentIndexByName.get(name);
    if (dependantIndex === undefined) {
      continue;
    }

    for (const dep of deps) {
      const dependencyIndex = componentIndexByName.get(dep);
      if (dependencyIndex === undefined || dependencyIndex === dependantIndex) {
        continue;
      }

      const neighbours = graph.get(dependencyIndex);
      if (!neighbours) {
        continue;
      }

      if (!neighbours.has(dependantIndex)) {
        neighbours.add(dependantIndex);
        inDegree.set(dependantIndex, (inDegree.get(dependantIndex) ?? 0) + 1);
      }
    }
  }

  const queue: number[] = [];
  for (const [index, degree] of inDegree.entries()) {
    if (degree === 0) {
      queue.push(index);
    }
  }

  const orderedIndices: number[] = [];
  while (queue.length > 0) {
    const current = queue.shift();
    if (current === undefined) {
      continue;
    }
    orderedIndices.push(current);

    for (const neighbour of graph.get(current) ?? []) {
      const nextDegree = (inDegree.get(neighbour) ?? 0) - 1;
      inDegree.set(neighbour, nextDegree);
      if (nextDegree === 0) {
        queue.push(neighbour);
      }
    }
  }

  if (orderedIndices.length !== scc.length) {
    throw new Error('Failed to order generated type declarations.');
  }

  return orderedIndices.map(index => scc[index]);
}

function stronglyConnectedComponents(names: string[], adjacency: Map<string, Set<string>>): string[][] {
  const components: string[][] = [];
  const indexMap = new Map<string, number>();
  const lowLinkMap = new Map<string, number>();
  const onStack = new Set<string>();
  const stack: string[] = [];
  let index = 0;

  const connect = (name: string) => {
    indexMap.set(name, index);
    lowLinkMap.set(name, index);
    index += 1;
    stack.push(name);
    onStack.add(name);

    for (const neighbour of adjacency.get(name) ?? []) {
      if (!indexMap.has(neighbour)) {
        connect(neighbour);
        const neighbourLowLink = lowLinkMap.get(neighbour);
        const currentLowLink = lowLinkMap.get(name) ?? Number.POSITIVE_INFINITY;
        if (neighbourLowLink !== undefined) {
          lowLinkMap.set(name, Math.min(currentLowLink, neighbourLowLink));
        }
      } else if (onStack.has(neighbour)) {
        const neighbourIndex = indexMap.get(neighbour);
        const currentLowLink = lowLinkMap.get(name) ?? Number.POSITIVE_INFINITY;
        if (neighbourIndex !== undefined) {
          lowLinkMap.set(name, Math.min(currentLowLink, neighbourIndex));
        }
      }
    }

    if (lowLinkMap.get(name) === indexMap.get(name)) {
      const component: string[] = [];
      let currentName: string | undefined;
      do {
        currentName = stack.pop();
        if (currentName === undefined) {
          break;
        }
        onStack.delete(currentName);
        component.push(currentName);
      } while (currentName !== name);
      components.push(component);
    }
  };

  for (const name of names) {
    if (!indexMap.has(name)) {
      connect(name);
    }
  }

  return components;
}

function packModules(components: string[][], declarations: DeclarationInfo[]): ModulePart[] {
  const declarationMap = new Map<string, DeclarationInfo>();
  declarations.forEach(declaration => {
    declarationMap.set(declaration.name, declaration);
  });

  const modules: ModulePart[] = [];
  let currentModule: ModulePart | null = null;

  const flush = () => {
    if (currentModule) {
      modules.push(currentModule);
      currentModule = null;
    }
  };

  components.forEach((component, componentIndex) => {
    const componentDeclarations = component
      .map(name => declarationMap.get(name))
      .filter((value): value is DeclarationInfo => Boolean(value))
      .sort((a, b) => a.order - b.order);

    const componentDeclarationCount = componentDeclarations.length;
    const componentCharLength = componentDeclarations.reduce((sum, decl) => sum + decl.charLength + 2, 0);

    if (!currentModule) {
      currentModule = {
        index: modules.length,
        names: [],
        declarations: [],
      };
    }

    const newDeclarationCount = currentModule.declarations.length + componentDeclarationCount;
    const newCharLength = currentModule.declarations.reduce((sum, decl) => sum + decl.charLength + 2, 0) + componentCharLength;

    if (
      currentModule.declarations.length > 0 &&
      (newDeclarationCount > MAX_DECLARATIONS_PER_FILE || newCharLength > MAX_CHARACTERS_PER_FILE)
    ) {
      flush();
      currentModule = {
        index: modules.length,
        names: [],
        declarations: [],
      };
    }

    currentModule.names.push(...componentDeclarations.map(declaration => declaration.name));
    currentModule.declarations.push(...componentDeclarations);

    if (componentIndex === components.length - 1) {
      flush();
    }
  });

  flush();

  return modules;
}

function buildModuleFile(module: ModulePart, modules: ModulePart[], moduleFileNames: Map<number, string>): GeneratedModule {
  const moduleIndexMap = new Map<string, number>();
  modules.forEach((part, partIndex) => {
    part.names.forEach(name => {
      moduleIndexMap.set(name, partIndex);
    });
  });

  const dependencyImports = new Map<number, Set<string>>();
  for (const declaration of module.declarations) {
    for (const dependency of declaration.dependencies) {
      const dependencyModuleIndex = moduleIndexMap.get(dependency);
      if (dependencyModuleIndex === undefined || dependencyModuleIndex === module.index) {
        continue;
      }

      if (!dependencyImports.has(dependencyModuleIndex)) {
        dependencyImports.set(dependencyModuleIndex, new Set());
      }

      const bucket = dependencyImports.get(dependencyModuleIndex);
      if (bucket) {
        bucket.add(dependency);
      }
    }
  }

  const fileName = moduleFileNames.get(module.index) ?? `module-${module.index + 1}.ts`;

  const lines: string[] = [];
  lines.push(BANNER_COMMENT.trimEnd());
  lines.push('');

  if (dependencyImports.size > 0) {
    const sortedImports = Array.from(dependencyImports.entries()).sort((a, b) => a[0] - b[0]);
    for (const [dependencyModuleIndex, names] of sortedImports) {
      const specifiers = Array.from(names).sort().join(', ');
      const dependencyFileName = moduleFileNames.get(dependencyModuleIndex);
      if (!dependencyFileName) {
        continue;
      }
      lines.push(`import type { ${specifiers} } from './${dependencyFileName}';`);
    }
    lines.push('');
  }

  for (const declaration of module.declarations) {
    lines.push(declaration.text.trim());
    lines.push('');
  }

  const content = `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;

  return {
    fileName,
    content,
    exports: [...module.names],
  };
}

function assignModuleFileNames(modules: ModulePart[]): Map<number, string> {
  const fileNames = new Map<number, string>();
  const usedSlugs = new Set<string>();

  modules.forEach(module => {
    const baseSlug = deriveModuleSlug(module);
    let candidate = baseSlug;
    let suffix = 2;

    while (usedSlugs.has(candidate)) {
      candidate = `${baseSlug}-${suffix}`;
      suffix += 1;
    }

    usedSlugs.add(candidate);
    fileNames.set(module.index, `${candidate}.ts`);
  });

  return fileNames;
}

function deriveModuleSlug(module: ModulePart): string {
  const fallback = `module-${module.index + 1}`;
  const [firstName] = module.names;
  if (!firstName) {
    return fallback;
  }

  const kebab = toKebabCase(firstName)
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');

  if (!kebab) {
    return fallback;
  }

  const truncated = kebab.length > MAX_SLUG_LENGTH ? kebab.slice(0, MAX_SLUG_LENGTH).replace(/-+$/g, '') : kebab;
  return truncated || fallback;
}

function toKebabCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

async function writeGeneratedArtifacts(result: ModuleGenerationResult): Promise<void> {
  await rm(GENERATED_DIR, { recursive: true, force: true });
  await mkdir(GENERATED_DIR, { recursive: true });

  for (const module of result.modules) {
    const filePath = resolve(GENERATED_DIR, module.fileName);
    await writeFile(filePath, module.content, 'utf8');
  }

  await writeFile(GENERATED_INDEX_PATH, result.indexContent, 'utf8');
  await writeFile(LEGACY_OUTPUT_PATH, result.legacyContent, 'utf8');
}
