import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { JSONSchema } from 'json-schema-to-typescript';
import { compile } from 'json-schema-to-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const BIOME_CONSTANTS_PATH = resolve(__dirname, '../src/constants/biome.ts');
const OUTPUT_PATH = resolve(__dirname, '../src/types.ts');

async function resolveSchemaUrl(): Promise<string> {
  const source = await readFile(BIOME_CONSTANTS_PATH, 'utf8');
  const match = source.match(/BIOME_SCHEMA_URL\s*=\s*['"]([^'"]+)['"]/);
  if (!match) {
    throw new Error(`Failed to resolve BIOME_SCHEMA_URL from ${BIOME_CONSTANTS_PATH}`);
  }
  return match[1];
}

async function fetchSchema(url: string): Promise<JSONSchema> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch schema from ${url}: ${response.status} ${response.statusText}`);
  }
  return response.json() as Promise<JSONSchema>;
}

async function generateTypes(): Promise<void> {
  const schemaUrl = await resolveSchemaUrl();
  const schema = await fetchSchema(schemaUrl);

  const bannerComment = `// This file was automatically generated by scripts/generate-biome-types.ts\n// Do not edit this file directly.\n`;

  let ts = await compile(schema, 'BiomeConfig', {
    bannerComment,
    style: {
      singleQuote: true,
      trailingComma: 'none',
    },
  });

  if (!ts.includes('export type BiomeConfig')) {
    ts = `${ts.trimEnd()}\n\nexport type BiomeConfig = Configuration;\n`;
  }

  await writeFile(OUTPUT_PATH, ts, 'utf8');
  console.log(`Generated BiomeConfig types at ${OUTPUT_PATH}`);
}

try {
  await generateTypes();
} catch (error) {
  console.error('Failed to generate BiomeConfig types.');
  console.error(error);
  process.exitCode = 1;
}
