import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { JSONSchema } from 'json-schema-to-typescript';
import { compile } from 'json-schema-to-typescript';
import ts from 'typescript';

import { updateBiomeConstantsFile } from './utils/biome-version.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GENERATED_DIR = resolve(__dirname, '../src/generated/biome');
const PATHS = {
  BIOME_CONSTANTS: resolve(__dirname, '../src/constants/biome.ts'),
  GENERATED_INDEX: resolve(GENERATED_DIR, 'index.ts'),
  LEGACY_OUTPUT: resolve(__dirname, '../src/types.ts'),
} as const;

const BANNER_COMMENT = `// This file was automatically generated by scripts/generate-biome-types.ts\n// Do not edit this file directly.\n`;
const BANNER_TRIMMED = BANNER_COMMENT.trimEnd();

const LIMITS = {
  MAX_CHARACTERS_PER_FILE: 45_000,
  MAX_DECLARATIONS_PER_FILE: 120,
  MAX_SLUG_LENGTH: 60,
} as const;

interface DeclarationInfo {
  name: string;
  text: string;
  dependencies: Set<string>;
  charLength: number;
  order: number;
}

interface ModulePart {
  index: number;
  names: string[];
  declarations: DeclarationInfo[];
}

interface GeneratedModule {
  fileName: string;
  content: string;
  exports: string[];
}

interface ModuleGenerationResult {
  modules: GeneratedModule[];
  indexContent: string;
  legacyContent: string;
}

async function fetchSchema(url: string): Promise<JSONSchema> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch schema from ${url}: ${response.status} ${response.statusText}`);
  }
  return response.json() as Promise<JSONSchema>;
}

async function generateTypes(): Promise<void> {
  // Update biome constants file first
  const { version: biomejsVersion, schemaUrl } = await updateBiomeConstantsFile();
  console.log(`Updated BIOME_SCHEMA_URL to version ${biomejsVersion}`);

  const schema = await fetchSchema(schemaUrl);

  let typeSource = await compile(schema, 'BiomeConfig', {
    bannerComment: BANNER_COMMENT,
    style: {
      singleQuote: true,
      trailingComma: 'none',
    },
  });

  if (!typeSource.includes('export type BiomeConfig')) {
    typeSource = `${typeSource.trimEnd()}\n\nexport type BiomeConfig = Configuration;\n`;
  }

  const generationResult = splitTypesIntoModules(typeSource);
  await writeGeneratedArtifacts(generationResult);

  console.log(`Generated BiomeConfig types at ${PATHS.LEGACY_OUTPUT}`);
}

try {
  await generateTypes();
} catch (error) {
  console.error('Failed to generate BiomeConfig types.');
  console.error(error);
  process.exitCode = 1;
}

function splitTypesIntoModules(source: string): ModuleGenerationResult {
  const trimmedSource = stripBanner(source, BANNER_COMMENT);
  const declarationNodes = collectDeclarations(trimmedSource);
  const declarations = enrichDeclarationsWithDependencies(declarationNodes);

  const adjacency = new Map(declarations.map(decl => [decl.name, new Set(decl.dependencies)]));
  const components = orderComponents(declarations, adjacency);
  const modules = packModules(components, declarations);
  const moduleFileNames = assignModuleFileNames(modules);
  const generatedModules = modules.map(module => buildModuleFile(module, modules, moduleFileNames));

  const indexContent = [BANNER_TRIMMED, '', ...generatedModules.map(module => `export * from './${module.fileName}';`), ''].join('\n');

  const legacyContent = [BANNER_TRIMMED, '', "export * from './generated/biome/index.ts';", ''].join('\n');

  return {
    indexContent,
    legacyContent,
    modules: generatedModules,
  };
}

function stripBanner(source: string, banner: string): string {
  return source.startsWith(banner) ? source.slice(banner.length).replace(/^\s*/, '') : source;
}

function collectDeclarations(source: string): Array<{
  name: string;
  text: string;
  node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration;
  order: number;
}> {
  const sourceFile = ts.createSourceFile('types.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const declarations: Array<{
    name: string;
    text: string;
    node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration;
    order: number;
  }> = [];

  let order = 0;
  for (const statement of sourceFile.statements) {
    if (!ts.isInterfaceDeclaration(statement) && !ts.isTypeAliasDeclaration(statement)) {
      continue;
    }

    const hasExport = statement.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword);
    if (!hasExport || !statement.name) {
      continue;
    }

    const name = statement.name.text;
    const text = source.slice(statement.getFullStart(), statement.getEnd()).trim();

    declarations.push({
      name,
      node: statement,
      order: order++,
      text,
    });
  }

  return declarations;
}

function enrichDeclarationsWithDependencies(
  entries: Array<{
    name: string;
    text: string;
    node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration;
    order: number;
  }>,
): DeclarationInfo[] {
  const nameSet = new Set(entries.map(entry => entry.name));

  return entries.map(entry => ({
    charLength: entry.text.length,
    dependencies: collectDependencies(entry.node, nameSet),
    name: entry.name,
    order: entry.order,
    text: entry.text,
  }));
}

function collectDependencies(node: ts.InterfaceDeclaration | ts.TypeAliasDeclaration, nameSet: Set<string>): Set<string> {
  const dependencies = new Set<string>();

  const record = (identifier: string) => {
    if (nameSet.has(identifier) && identifier !== node.name.text) {
      dependencies.add(identifier);
    }
  };

  const visit = (child: ts.Node) => {
    if (ts.isTypeReferenceNode(child)) {
      extractNamesFromTypeReference(child).forEach(record);
    } else if (ts.isExpressionWithTypeArguments(child)) {
      const expr = child.expression;
      if (ts.isIdentifier(expr)) {
        record(expr.text);
      } else if (ts.isPropertyAccessExpression(expr)) {
        record(expr.name.text);
      }
    } else if (ts.isImportTypeNode(child)) {
      if (child.qualifier && ts.isIdentifier(child.qualifier)) {
        record(child.qualifier.text);
      }
    }

    ts.forEachChild(child, visit);
  };

  ts.forEachChild(node, visit);

  return dependencies;
}

function extractNamesFromTypeReference(node: ts.TypeReferenceNode): string[] {
  const names: string[] = [];
  const { typeName } = node;

  const collect = (entity: ts.EntityName) => {
    if (ts.isIdentifier(entity)) {
      names.push(entity.text);
    } else if (ts.isQualifiedName(entity)) {
      collect(entity.left);
      names.push(entity.right.text);
    }
  };

  if (ts.isIdentifier(typeName)) {
    names.push(typeName.text);
  } else {
    collect(typeName);
  }

  return names;
}

function orderComponents(declarations: DeclarationInfo[], adjacency: Map<string, Set<string>>): string[][] {
  const names = declarations.map(decl => decl.name);
  const scc = stronglyConnectedComponents(names, adjacency);
  const componentIndexByName = new Map<string, number>();
  scc.forEach((component, index) => {
    for (const name of component) {
      componentIndexByName.set(name, index);
    }
  });

  const componentCount = scc.length;
  const graph = new Map<number, Set<number>>();
  const inDegree = new Map<number, number>();

  // Initialize graph and inDegree
  for (let i = 0; i < componentCount; i++) {
    graph.set(i, new Set());
    inDegree.set(i, 0);
  }

  for (const [name, deps] of adjacency.entries()) {
    const dependantIndex = componentIndexByName.get(name);
    if (dependantIndex === undefined) {
      continue;
    }

    for (const dep of deps) {
      const dependencyIndex = componentIndexByName.get(dep);
      if (dependencyIndex === undefined || dependencyIndex === dependantIndex) {
        continue;
      }

      const neighbours = graph.get(dependencyIndex);
      if (!neighbours) {
        continue;
      }

      if (!neighbours.has(dependantIndex)) {
        neighbours.add(dependantIndex);
        inDegree.set(dependantIndex, (inDegree.get(dependantIndex) ?? 0) + 1);
      }
    }
  }

  const queue: number[] = [];
  for (const [index, degree] of inDegree.entries()) {
    if (degree === 0) {
      queue.push(index);
    }
  }

  const orderedIndices: number[] = [];
  for (let i = 0; i < queue.length; ) {
    const current = queue[i];
    orderedIndices.push(current);

    for (const neighbour of graph.get(current) ?? []) {
      const nextDegree = (inDegree.get(neighbour) ?? 0) - 1;
      inDegree.set(neighbour, nextDegree);
      if (nextDegree === 0) {
        queue.push(neighbour);
      }
    }
    i++;
  }

  if (orderedIndices.length !== scc.length) {
    throw new Error('Failed to order generated type declarations.');
  }

  return orderedIndices.map(index => scc[index]);
}

function stronglyConnectedComponents(names: string[], adjacency: Map<string, Set<string>>): string[][] {
  const components: string[][] = [];
  const indexMap = new Map<string, number>();
  const lowLinkMap = new Map<string, number>();
  const onStack = new Set<string>();
  const stack: string[] = [];
  let index = 0;

  const connect = (name: string) => {
    indexMap.set(name, index);
    lowLinkMap.set(name, index);
    index += 1;
    stack.push(name);
    onStack.add(name);

    for (const neighbour of adjacency.get(name) ?? []) {
      if (!indexMap.has(neighbour)) {
        connect(neighbour);
        const neighbourLowLink = lowLinkMap.get(neighbour);
        const currentLowLink = lowLinkMap.get(name) ?? Number.POSITIVE_INFINITY;
        if (neighbourLowLink !== undefined) {
          lowLinkMap.set(name, Math.min(currentLowLink, neighbourLowLink));
        }
      } else if (onStack.has(neighbour)) {
        const neighbourIndex = indexMap.get(neighbour);
        const currentLowLink = lowLinkMap.get(name) ?? Number.POSITIVE_INFINITY;
        if (neighbourIndex !== undefined) {
          lowLinkMap.set(name, Math.min(currentLowLink, neighbourIndex));
        }
      }
    }

    if (lowLinkMap.get(name) === indexMap.get(name)) {
      const component: string[] = [];
      let currentName = stack.pop();
      while (currentName !== undefined) {
        onStack.delete(currentName);
        component.push(currentName);
        if (currentName === name) break;
        currentName = stack.pop();
      }
      components.push(component);
    }
  };

  for (const name of names) {
    if (!indexMap.has(name)) {
      connect(name);
    }
  }

  return components;
}

function packModules(components: string[][], declarations: DeclarationInfo[]): ModulePart[] {
  const declarationMap = new Map(declarations.map(decl => [decl.name, decl]));
  const modules: ModulePart[] = [];
  let currentModule: ModulePart | null = null;

  const calculateCharLength = (declarations: DeclarationInfo[]) => declarations.reduce((sum, decl) => sum + decl.charLength + 2, 0);

  const createNewModule = (): ModulePart => ({
    declarations: [],
    index: modules.length,
    names: [],
  });

  const flush = () => {
    if (currentModule) {
      modules.push(currentModule);
      currentModule = null;
    }
  };

  components.forEach((component, componentIndex) => {
    const componentDeclarations = component
      .map(name => declarationMap.get(name))
      .filter((value): value is DeclarationInfo => Boolean(value))
      .sort((a, b) => a.order - b.order);

    const componentDeclarationCount = componentDeclarations.length;
    const componentCharLength = calculateCharLength(componentDeclarations);

    if (!currentModule) {
      currentModule = createNewModule();
    }

    const newDeclarationCount = currentModule.declarations.length + componentDeclarationCount;
    const newCharLength = calculateCharLength(currentModule.declarations) + componentCharLength;

    if (
      currentModule.declarations.length > 0 &&
      (newDeclarationCount > LIMITS.MAX_DECLARATIONS_PER_FILE || newCharLength > LIMITS.MAX_CHARACTERS_PER_FILE)
    ) {
      flush();
      currentModule = createNewModule();
    }

    currentModule.names.push(...componentDeclarations.map(declaration => declaration.name));
    currentModule.declarations.push(...componentDeclarations);

    if (componentIndex === components.length - 1) {
      flush();
    }
  });

  flush();

  return modules;
}

function buildModuleFile(module: ModulePart, modules: ModulePart[], moduleFileNames: Map<number, string>): GeneratedModule {
  const moduleIndexMap = new Map<string, number>();
  modules.forEach((part, partIndex) => {
    for (const name of part.names) {
      moduleIndexMap.set(name, partIndex);
    }
  });

  const dependencyImports = new Map<number, Set<string>>();
  for (const declaration of module.declarations) {
    for (const dependency of declaration.dependencies) {
      const dependencyModuleIndex = moduleIndexMap.get(dependency);
      if (dependencyModuleIndex === undefined || dependencyModuleIndex === module.index) {
        continue;
      }

      const bucket = dependencyImports.get(dependencyModuleIndex) ?? new Set<string>();
      bucket.add(dependency);
      dependencyImports.set(dependencyModuleIndex, bucket);
    }
  }

  const fileName = moduleFileNames.get(module.index) ?? `module-${module.index + 1}.ts`;

  const lines: string[] = [BANNER_TRIMMED, ''];

  if (dependencyImports.size > 0) {
    const sortedImports = Array.from(dependencyImports.entries()).sort((a, b) => a[0] - b[0]);
    for (const [dependencyModuleIndex, names] of sortedImports) {
      const specifiers = Array.from(names).sort().join(', ');
      const dependencyFileName = moduleFileNames.get(dependencyModuleIndex);
      if (!dependencyFileName) {
        continue;
      }
      lines.push(`import type { ${specifiers} } from './${dependencyFileName}';`);
    }
    lines.push('');
  }

  for (const declaration of module.declarations) {
    lines.push(declaration.text.trim());
    lines.push('');
  }

  const content = `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;

  return {
    content,
    exports: [...module.names],
    fileName,
  };
}

function assignModuleFileNames(modules: ModulePart[]): Map<number, string> {
  const fileNames = new Map<number, string>();
  const usedSlugs = new Set<string>();

  modules.forEach(module => {
    const baseSlug = deriveModuleSlug(module);
    let candidate = baseSlug;
    let suffix = 2;

    while (usedSlugs.has(candidate)) {
      candidate = `${baseSlug}-${suffix}`;
      suffix += 1;
    }

    usedSlugs.add(candidate);
    fileNames.set(module.index, `${candidate}.ts`);
  });

  return fileNames;
}

function deriveModuleSlug(module: ModulePart): string {
  const fallback = `module-${module.index + 1}`;
  const [firstName] = module.names;
  if (!firstName) return fallback;

  const kebab = toKebabCase(firstName)
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');

  if (!kebab) return fallback;

  const truncated = kebab.length > LIMITS.MAX_SLUG_LENGTH ? kebab.slice(0, LIMITS.MAX_SLUG_LENGTH).replace(/-+$/g, '') : kebab;
  return truncated || fallback;
}

function toKebabCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

async function writeGeneratedArtifacts(result: ModuleGenerationResult): Promise<void> {
  await rm(GENERATED_DIR, { force: true, recursive: true });
  await mkdir(GENERATED_DIR, { recursive: true });

  for (const module of result.modules) {
    const filePath = resolve(GENERATED_DIR, module.fileName);
    await writeFile(filePath, module.content, 'utf8');
  }

  await writeFile(PATHS.GENERATED_INDEX, result.indexContent, 'utf8');
  await writeFile(PATHS.LEGACY_OUTPUT, result.legacyContent, 'utf8');
}
